# Generated by Django 3.2 on 2021-07-31 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kb_backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='owner',
        ),
    ]
