# Generated by Django 3.2 on 2021-07-31 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kb_backend', '0003_campaign_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='owner',
        ),
    ]
