# Generated by Django 4.1.5 on 2023-02-09 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kb_backend', '0011_campaign_gtag_campaign_image_alter_campaign_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='options',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
