# Generated by Django 4.1.5 on 2023-02-09 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb_backend', '0012_campaign_options_alter_campaign_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='options',
            field=models.CharField(default='', max_length=800),
        ),
    ]
