# Generated by Django 4.1.5 on 2023-03-17 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kb_backend', '0014_invitationlink'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InvitationLink',
            new_name='Invitation',
        ),
    ]
