# Generated by Django 4.1.5 on 2023-03-17 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb_backend', '0015_rename_invitationlink_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='email',
            field=models.EmailField(default='random', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
